//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDataTRH.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", ConfigurationName="ServiceReference1.NuevaListaProductos_Port")]
    public interface NuevaListaProductos_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.Read_Result Read(ModelDataTRH.ServiceReference1.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Read_Result> ReadAsync(ModelDataTRH.ServiceReference1.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.ReadByRecId_Result ReadByRecId(ModelDataTRH.ServiceReference1.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(ModelDataTRH.ServiceReference1.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.ReadMultiple_Result ReadMultiple(ModelDataTRH.ServiceReference1.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ModelDataTRH.ServiceReference1.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.IsUpdated_Result IsUpdated(ModelDataTRH.ServiceReference1.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.IsUpdated_Result> IsUpdatedAsync(ModelDataTRH.ServiceReference1.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.GetRecIdFromKey_Result GetRecIdFromKey(ModelDataTRH.ServiceReference1.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ModelDataTRH.ServiceReference1.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.Create_Result Create(ModelDataTRH.ServiceReference1.Create request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Create_Result> CreateAsync(ModelDataTRH.ServiceReference1.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.CreateMultiple_Result CreateMultiple(ModelDataTRH.ServiceReference1.CreateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ModelDataTRH.ServiceReference1.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.Update_Result Update(ModelDataTRH.ServiceReference1.Update request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Update_Result> UpdateAsync(ModelDataTRH.ServiceReference1.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.UpdateMultiple_Result UpdateMultiple(ModelDataTRH.ServiceReference1.UpdateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ModelDataTRH.ServiceReference1.UpdateMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Delete_Result) del mensaje Delete_Result no coincide con el valor predeterminado (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ModelDataTRH.ServiceReference1.Delete_Result Delete(ModelDataTRH.ServiceReference1.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/nuevalistaproductos:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Delete_Result> DeleteAsync(ModelDataTRH.ServiceReference1.Delete request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos")]
    public partial class NuevaListaProductos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string buy_from_Vendor_NoField;
        
        private string buy_from_Vendor_NameField;
        
        private decimal cantidad_Pdt_FacturarField;
        
        private bool cantidad_Pdt_FacturarFieldSpecified;
        
        private decimal cantidad_a_RecibirField;
        
        private bool cantidad_a_RecibirFieldSpecified;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private string codigoPedidoCabeceraField;
        
        private string ref_BarcoField;
        
        private bool firma_DireccionField;
        
        private bool firma_DireccionFieldSpecified;
        
        private System.DateTime fecha_FirmaField;
        
        private bool fecha_FirmaFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string vendor_Invoice_NoField;
        
        private string buy_from_Post_CodeField;
        
        private string buy_from_Country_Region_CodeField;
        
        private string buy_from_ContactField;
        
        private string pay_to_Vendor_NoField;
        
        private string ship_to_CityField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string location_CodeField;
        
        private string purchaser_CodeField;
        
        private string assigned_User_IDField;
        
        private string currency_CodeField;
        
        private System.DateTime due_DateField;
        
        private bool due_DateFieldSpecified;
        
        private System.DateTime fecha_EmbarqueField;
        
        private bool fecha_EmbarqueFieldSpecified;
        
        private string last_Receiving_NoField;
        
        private System.DateTime fecha_LLegadaField;
        
        private bool fecha_LLegadaFieldSpecified;
        
        private string order_Address_CodeField;
        
        private decimal cantidad_TotalField;
        
        private bool cantidad_TotalFieldSpecified;
        
        private decimal importe_Total_PedidoField;
        
        private bool importe_Total_PedidoFieldSpecified;
        
        private int nº_Ped_Venta_AsignadosField;
        
        private bool nº_Ped_Venta_AsignadosFieldSpecified;
        
        private string vendor_Authorization_NoField;
        
        private string pay_to_NameField;
        
        private string pay_to_Post_CodeField;
        
        private string pay_to_Country_Region_CodeField;
        
        private string pay_to_ContactField;
        
        private string ship_to_CodeField;
        
        private string ship_to_NameField;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_Country_Region_CodeField;
        
        private string ship_to_ContactField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Buy_from_Vendor_No {
            get {
                return this.buy_from_Vendor_NoField;
            }
            set {
                this.buy_from_Vendor_NoField = value;
                this.RaisePropertyChanged("Buy_from_Vendor_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Buy_from_Vendor_Name {
            get {
                return this.buy_from_Vendor_NameField;
            }
            set {
                this.buy_from_Vendor_NameField = value;
                this.RaisePropertyChanged("Buy_from_Vendor_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Cantidad_Pdt_Facturar {
            get {
                return this.cantidad_Pdt_FacturarField;
            }
            set {
                this.cantidad_Pdt_FacturarField = value;
                this.RaisePropertyChanged("Cantidad_Pdt_Facturar");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cantidad_Pdt_FacturarSpecified {
            get {
                return this.cantidad_Pdt_FacturarFieldSpecified;
            }
            set {
                this.cantidad_Pdt_FacturarFieldSpecified = value;
                this.RaisePropertyChanged("Cantidad_Pdt_FacturarSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Cantidad_a_Recibir {
            get {
                return this.cantidad_a_RecibirField;
            }
            set {
                this.cantidad_a_RecibirField = value;
                this.RaisePropertyChanged("Cantidad_a_Recibir");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cantidad_a_RecibirSpecified {
            get {
                return this.cantidad_a_RecibirFieldSpecified;
            }
            set {
                this.cantidad_a_RecibirFieldSpecified = value;
                this.RaisePropertyChanged("Cantidad_a_RecibirSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
                this.RaisePropertyChanged("Posting_Date");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Posting_DateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CodigoPedidoCabecera {
            get {
                return this.codigoPedidoCabeceraField;
            }
            set {
                this.codigoPedidoCabeceraField = value;
                this.RaisePropertyChanged("CodigoPedidoCabecera");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Ref_Barco {
            get {
                return this.ref_BarcoField;
            }
            set {
                this.ref_BarcoField = value;
                this.RaisePropertyChanged("Ref_Barco");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Firma_Direccion {
            get {
                return this.firma_DireccionField;
            }
            set {
                this.firma_DireccionField = value;
                this.RaisePropertyChanged("Firma_Direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Firma_DireccionSpecified {
            get {
                return this.firma_DireccionFieldSpecified;
            }
            set {
                this.firma_DireccionFieldSpecified = value;
                this.RaisePropertyChanged("Firma_DireccionSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime Fecha_Firma {
            get {
                return this.fecha_FirmaField;
            }
            set {
                this.fecha_FirmaField = value;
                this.RaisePropertyChanged("Fecha_Firma");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fecha_FirmaSpecified {
            get {
                return this.fecha_FirmaFieldSpecified;
            }
            set {
                this.fecha_FirmaFieldSpecified = value;
                this.RaisePropertyChanged("Fecha_FirmaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Vendor_Invoice_No {
            get {
                return this.vendor_Invoice_NoField;
            }
            set {
                this.vendor_Invoice_NoField = value;
                this.RaisePropertyChanged("Vendor_Invoice_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Buy_from_Post_Code {
            get {
                return this.buy_from_Post_CodeField;
            }
            set {
                this.buy_from_Post_CodeField = value;
                this.RaisePropertyChanged("Buy_from_Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Buy_from_Country_Region_Code {
            get {
                return this.buy_from_Country_Region_CodeField;
            }
            set {
                this.buy_from_Country_Region_CodeField = value;
                this.RaisePropertyChanged("Buy_from_Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Buy_from_Contact {
            get {
                return this.buy_from_ContactField;
            }
            set {
                this.buy_from_ContactField = value;
                this.RaisePropertyChanged("Buy_from_Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Pay_to_Vendor_No {
            get {
                return this.pay_to_Vendor_NoField;
            }
            set {
                this.pay_to_Vendor_NoField = value;
                this.RaisePropertyChanged("Pay_to_Vendor_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Ship_to_City {
            get {
                return this.ship_to_CityField;
            }
            set {
                this.ship_to_CityField = value;
                this.RaisePropertyChanged("Ship_to_City");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
                this.RaisePropertyChanged("Shortcut_Dimension_1_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
                this.RaisePropertyChanged("Shortcut_Dimension_2_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Purchaser_Code {
            get {
                return this.purchaser_CodeField;
            }
            set {
                this.purchaser_CodeField = value;
                this.RaisePropertyChanged("Purchaser_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Assigned_User_ID {
            get {
                return this.assigned_User_IDField;
            }
            set {
                this.assigned_User_IDField = value;
                this.RaisePropertyChanged("Assigned_User_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
                this.RaisePropertyChanged("Currency_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=24)]
        public System.DateTime Due_Date {
            get {
                return this.due_DateField;
            }
            set {
                this.due_DateField = value;
                this.RaisePropertyChanged("Due_Date");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Due_DateSpecified {
            get {
                return this.due_DateFieldSpecified;
            }
            set {
                this.due_DateFieldSpecified = value;
                this.RaisePropertyChanged("Due_DateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=25)]
        public System.DateTime Fecha_Embarque {
            get {
                return this.fecha_EmbarqueField;
            }
            set {
                this.fecha_EmbarqueField = value;
                this.RaisePropertyChanged("Fecha_Embarque");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fecha_EmbarqueSpecified {
            get {
                return this.fecha_EmbarqueFieldSpecified;
            }
            set {
                this.fecha_EmbarqueFieldSpecified = value;
                this.RaisePropertyChanged("Fecha_EmbarqueSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Last_Receiving_No {
            get {
                return this.last_Receiving_NoField;
            }
            set {
                this.last_Receiving_NoField = value;
                this.RaisePropertyChanged("Last_Receiving_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=27)]
        public System.DateTime Fecha_LLegada {
            get {
                return this.fecha_LLegadaField;
            }
            set {
                this.fecha_LLegadaField = value;
                this.RaisePropertyChanged("Fecha_LLegada");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Fecha_LLegadaSpecified {
            get {
                return this.fecha_LLegadaFieldSpecified;
            }
            set {
                this.fecha_LLegadaFieldSpecified = value;
                this.RaisePropertyChanged("Fecha_LLegadaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Order_Address_Code {
            get {
                return this.order_Address_CodeField;
            }
            set {
                this.order_Address_CodeField = value;
                this.RaisePropertyChanged("Order_Address_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal Cantidad_Total {
            get {
                return this.cantidad_TotalField;
            }
            set {
                this.cantidad_TotalField = value;
                this.RaisePropertyChanged("Cantidad_Total");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cantidad_TotalSpecified {
            get {
                return this.cantidad_TotalFieldSpecified;
            }
            set {
                this.cantidad_TotalFieldSpecified = value;
                this.RaisePropertyChanged("Cantidad_TotalSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal Importe_Total_Pedido {
            get {
                return this.importe_Total_PedidoField;
            }
            set {
                this.importe_Total_PedidoField = value;
                this.RaisePropertyChanged("Importe_Total_Pedido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Importe_Total_PedidoSpecified {
            get {
                return this.importe_Total_PedidoFieldSpecified;
            }
            set {
                this.importe_Total_PedidoFieldSpecified = value;
                this.RaisePropertyChanged("Importe_Total_PedidoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int Nº_Ped_Venta_Asignados {
            get {
                return this.nº_Ped_Venta_AsignadosField;
            }
            set {
                this.nº_Ped_Venta_AsignadosField = value;
                this.RaisePropertyChanged("Nº_Ped_Venta_Asignados");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Nº_Ped_Venta_AsignadosSpecified {
            get {
                return this.nº_Ped_Venta_AsignadosFieldSpecified;
            }
            set {
                this.nº_Ped_Venta_AsignadosFieldSpecified = value;
                this.RaisePropertyChanged("Nº_Ped_Venta_AsignadosSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Vendor_Authorization_No {
            get {
                return this.vendor_Authorization_NoField;
            }
            set {
                this.vendor_Authorization_NoField = value;
                this.RaisePropertyChanged("Vendor_Authorization_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Pay_to_Name {
            get {
                return this.pay_to_NameField;
            }
            set {
                this.pay_to_NameField = value;
                this.RaisePropertyChanged("Pay_to_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Pay_to_Post_Code {
            get {
                return this.pay_to_Post_CodeField;
            }
            set {
                this.pay_to_Post_CodeField = value;
                this.RaisePropertyChanged("Pay_to_Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Pay_to_Country_Region_Code {
            get {
                return this.pay_to_Country_Region_CodeField;
            }
            set {
                this.pay_to_Country_Region_CodeField = value;
                this.RaisePropertyChanged("Pay_to_Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Pay_to_Contact {
            get {
                return this.pay_to_ContactField;
            }
            set {
                this.pay_to_ContactField = value;
                this.RaisePropertyChanged("Pay_to_Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Ship_to_Code {
            get {
                return this.ship_to_CodeField;
            }
            set {
                this.ship_to_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Ship_to_Name {
            get {
                return this.ship_to_NameField;
            }
            set {
                this.ship_to_NameField = value;
                this.RaisePropertyChanged("Ship_to_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Ship_to_Post_Code {
            get {
                return this.ship_to_Post_CodeField;
            }
            set {
                this.ship_to_Post_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Ship_to_Country_Region_Code {
            get {
                return this.ship_to_Country_Region_CodeField;
            }
            set {
                this.ship_to_Country_Region_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string Ship_to_Contact {
            get {
                return this.ship_to_ContactField;
            }
            set {
                this.ship_to_ContactField = value;
                this.RaisePropertyChanged("Ship_to_Contact");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos")]
    public enum Status {
        
        /// <comentarios/>
        Open,
        
        /// <comentarios/>
        Released,
        
        /// <comentarios/>
        Pending_Approval,
        
        /// <comentarios/>
        Pending_Prepayment,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos")]
    public partial class NuevaListaProductos_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NuevaListaProductos_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NuevaListaProductos_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos")]
    public enum NuevaListaProductos_Fields {
        
        /// <comentarios/>
        No,
        
        /// <comentarios/>
        Buy_from_Vendor_No,
        
        /// <comentarios/>
        Buy_from_Vendor_Name,
        
        /// <comentarios/>
        Cantidad_Pdt_Facturar,
        
        /// <comentarios/>
        Cantidad_a_Recibir,
        
        /// <comentarios/>
        Posting_Date,
        
        /// <comentarios/>
        CodigoPedidoCabecera,
        
        /// <comentarios/>
        Ref_Barco,
        
        /// <comentarios/>
        Firma_Direccion,
        
        /// <comentarios/>
        Fecha_Firma,
        
        /// <comentarios/>
        Status,
        
        /// <comentarios/>
        Vendor_Invoice_No,
        
        /// <comentarios/>
        Buy_from_Post_Code,
        
        /// <comentarios/>
        Buy_from_Country_Region_Code,
        
        /// <comentarios/>
        Buy_from_Contact,
        
        /// <comentarios/>
        Pay_to_Vendor_No,
        
        /// <comentarios/>
        Ship_to_City,
        
        /// <comentarios/>
        Shortcut_Dimension_1_Code,
        
        /// <comentarios/>
        Shortcut_Dimension_2_Code,
        
        /// <comentarios/>
        Location_Code,
        
        /// <comentarios/>
        Purchaser_Code,
        
        /// <comentarios/>
        Assigned_User_ID,
        
        /// <comentarios/>
        Currency_Code,
        
        /// <comentarios/>
        Due_Date,
        
        /// <comentarios/>
        Fecha_Embarque,
        
        /// <comentarios/>
        Last_Receiving_No,
        
        /// <comentarios/>
        Fecha_LLegada,
        
        /// <comentarios/>
        Order_Address_Code,
        
        /// <comentarios/>
        Cantidad_Total,
        
        /// <comentarios/>
        Importe_Total_Pedido,
        
        /// <comentarios/>
        N_x00BA__Ped_Venta_Asignados,
        
        /// <comentarios/>
        Vendor_Authorization_No,
        
        /// <comentarios/>
        Pay_to_Name,
        
        /// <comentarios/>
        Pay_to_Post_Code,
        
        /// <comentarios/>
        Pay_to_Country_Region_Code,
        
        /// <comentarios/>
        Pay_to_Contact,
        
        /// <comentarios/>
        Ship_to_Code,
        
        /// <comentarios/>
        Ship_to_Name,
        
        /// <comentarios/>
        Ship_to_Post_Code,
        
        /// <comentarios/>
        Ship_to_Country_Region_Code,
        
        /// <comentarios/>
        Ship_to_Contact,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos;
        
        public Read_Result() {
        }
        
        public Read_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            this.NuevaListaProductos = NuevaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            this.NuevaListaProductos = NuevaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ModelDataTRH.ServiceReference1.NuevaListaProductos_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos;
        
        public Create() {
        }
        
        public Create(ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            this.NuevaListaProductos = NuevaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos;
        
        public Create_Result() {
        }
        
        public Create_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            this.NuevaListaProductos = NuevaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List) {
            this.NuevaListaProductos_List = NuevaListaProductos_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List) {
            this.NuevaListaProductos_List = NuevaListaProductos_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos;
        
        public Update() {
        }
        
        public Update(ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            this.NuevaListaProductos = NuevaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos;
        
        public Update_Result() {
        }
        
        public Update_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            this.NuevaListaProductos = NuevaListaProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List) {
            this.NuevaListaProductos_List = NuevaListaProductos_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List) {
            this.NuevaListaProductos_List = NuevaListaProductos_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/nuevalistaproductos", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NuevaListaProductos_PortChannel : ModelDataTRH.ServiceReference1.NuevaListaProductos_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NuevaListaProductos_PortClient : System.ServiceModel.ClientBase<ModelDataTRH.ServiceReference1.NuevaListaProductos_Port>, ModelDataTRH.ServiceReference1.NuevaListaProductos_Port {
        
        public NuevaListaProductos_PortClient() {
        }
        
        public NuevaListaProductos_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NuevaListaProductos_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NuevaListaProductos_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NuevaListaProductos_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.Read_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.Read(ModelDataTRH.ServiceReference1.Read request) {
            return base.Channel.Read(request);
        }
        
        public ModelDataTRH.ServiceReference1.NuevaListaProductos Read(string No) {
            ModelDataTRH.ServiceReference1.Read inValue = new ModelDataTRH.ServiceReference1.Read();
            inValue.No = No;
            ModelDataTRH.ServiceReference1.Read_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).Read(inValue);
            return retVal.NuevaListaProductos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Read_Result> ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.ReadAsync(ModelDataTRH.ServiceReference1.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Read_Result> ReadAsync(string No) {
            ModelDataTRH.ServiceReference1.Read inValue = new ModelDataTRH.ServiceReference1.Read();
            inValue.No = No;
            return ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.ReadByRecId_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.ReadByRecId(ModelDataTRH.ServiceReference1.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ModelDataTRH.ServiceReference1.NuevaListaProductos ReadByRecId(string recId) {
            ModelDataTRH.ServiceReference1.ReadByRecId inValue = new ModelDataTRH.ServiceReference1.ReadByRecId();
            inValue.recId = recId;
            ModelDataTRH.ServiceReference1.ReadByRecId_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).ReadByRecId(inValue);
            return retVal.NuevaListaProductos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.ReadByRecId_Result> ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.ReadByRecIdAsync(ModelDataTRH.ServiceReference1.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ModelDataTRH.ServiceReference1.ReadByRecId inValue = new ModelDataTRH.ServiceReference1.ReadByRecId();
            inValue.recId = recId;
            return ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.ReadMultiple_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.ReadMultiple(ModelDataTRH.ServiceReference1.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ModelDataTRH.ServiceReference1.NuevaListaProductos[] ReadMultiple(ModelDataTRH.ServiceReference1.NuevaListaProductos_Filter[] filter, string bookmarkKey, int setSize) {
            ModelDataTRH.ServiceReference1.ReadMultiple inValue = new ModelDataTRH.ServiceReference1.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ModelDataTRH.ServiceReference1.ReadMultiple_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.ReadMultiple_Result> ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.ReadMultipleAsync(ModelDataTRH.ServiceReference1.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ModelDataTRH.ServiceReference1.NuevaListaProductos_Filter[] filter, string bookmarkKey, int setSize) {
            ModelDataTRH.ServiceReference1.ReadMultiple inValue = new ModelDataTRH.ServiceReference1.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.IsUpdated_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.IsUpdated(ModelDataTRH.ServiceReference1.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ModelDataTRH.ServiceReference1.IsUpdated inValue = new ModelDataTRH.ServiceReference1.IsUpdated();
            inValue.Key = Key;
            ModelDataTRH.ServiceReference1.IsUpdated_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.IsUpdated_Result> ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.IsUpdatedAsync(ModelDataTRH.ServiceReference1.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ModelDataTRH.ServiceReference1.IsUpdated inValue = new ModelDataTRH.ServiceReference1.IsUpdated();
            inValue.Key = Key;
            return ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.GetRecIdFromKey_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.GetRecIdFromKey(ModelDataTRH.ServiceReference1.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ModelDataTRH.ServiceReference1.GetRecIdFromKey inValue = new ModelDataTRH.ServiceReference1.GetRecIdFromKey();
            inValue.Key = Key;
            ModelDataTRH.ServiceReference1.GetRecIdFromKey_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.GetRecIdFromKey_Result> ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.GetRecIdFromKeyAsync(ModelDataTRH.ServiceReference1.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ModelDataTRH.ServiceReference1.GetRecIdFromKey inValue = new ModelDataTRH.ServiceReference1.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.Create_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.Create(ModelDataTRH.ServiceReference1.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            ModelDataTRH.ServiceReference1.Create inValue = new ModelDataTRH.ServiceReference1.Create();
            inValue.NuevaListaProductos = NuevaListaProductos;
            ModelDataTRH.ServiceReference1.Create_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).Create(inValue);
            NuevaListaProductos = retVal.NuevaListaProductos;
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Create_Result> CreateAsync(ModelDataTRH.ServiceReference1.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.CreateMultiple_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.CreateMultiple(ModelDataTRH.ServiceReference1.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List) {
            ModelDataTRH.ServiceReference1.CreateMultiple inValue = new ModelDataTRH.ServiceReference1.CreateMultiple();
            inValue.NuevaListaProductos_List = NuevaListaProductos_List;
            ModelDataTRH.ServiceReference1.CreateMultiple_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).CreateMultiple(inValue);
            NuevaListaProductos_List = retVal.NuevaListaProductos_List;
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ModelDataTRH.ServiceReference1.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.Update_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.Update(ModelDataTRH.ServiceReference1.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ModelDataTRH.ServiceReference1.NuevaListaProductos NuevaListaProductos) {
            ModelDataTRH.ServiceReference1.Update inValue = new ModelDataTRH.ServiceReference1.Update();
            inValue.NuevaListaProductos = NuevaListaProductos;
            ModelDataTRH.ServiceReference1.Update_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).Update(inValue);
            NuevaListaProductos = retVal.NuevaListaProductos;
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Update_Result> UpdateAsync(ModelDataTRH.ServiceReference1.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.UpdateMultiple_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.UpdateMultiple(ModelDataTRH.ServiceReference1.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ModelDataTRH.ServiceReference1.NuevaListaProductos[] NuevaListaProductos_List) {
            ModelDataTRH.ServiceReference1.UpdateMultiple inValue = new ModelDataTRH.ServiceReference1.UpdateMultiple();
            inValue.NuevaListaProductos_List = NuevaListaProductos_List;
            ModelDataTRH.ServiceReference1.UpdateMultiple_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).UpdateMultiple(inValue);
            NuevaListaProductos_List = retVal.NuevaListaProductos_List;
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ModelDataTRH.ServiceReference1.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelDataTRH.ServiceReference1.Delete_Result ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.Delete(ModelDataTRH.ServiceReference1.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ModelDataTRH.ServiceReference1.Delete inValue = new ModelDataTRH.ServiceReference1.Delete();
            inValue.Key = Key;
            ModelDataTRH.ServiceReference1.Delete_Result retVal = ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Delete_Result> ModelDataTRH.ServiceReference1.NuevaListaProductos_Port.DeleteAsync(ModelDataTRH.ServiceReference1.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelDataTRH.ServiceReference1.Delete_Result> DeleteAsync(string Key) {
            ModelDataTRH.ServiceReference1.Delete inValue = new ModelDataTRH.ServiceReference1.Delete();
            inValue.Key = Key;
            return ((ModelDataTRH.ServiceReference1.NuevaListaProductos_Port)(this)).DeleteAsync(inValue);
        }
    }
}
