//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryWebServiceTRH.AlmacenRepuestosContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", ConfigurationName="AlmacenRepuestosContext.AlmacenRepuestos_Port")]
    public interface AlmacenRepuestos_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (RegistrarEntrega_Result) del mensaje RegistrarEntrega_Result no coincide con el valor predeterminado (RegistrarEntrega)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:RegistrarEntrega", ReplyAction="*")]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result RegistrarEntrega(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:RegistrarEntrega", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result> RegistrarEntregaAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarEntrega", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class RegistrarEntrega {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string codEmpleado;
        
        public RegistrarEntrega() {
        }
        
        public RegistrarEntrega(string codEmpleado) {
            this.codEmpleado = codEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarEntrega_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class RegistrarEntrega_Result {
        
        public RegistrarEntrega_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenRepuestos_PortChannel : RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenRepuestos_PortClient : System.ServiceModel.ClientBase<RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port>, RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port {
        
        public AlmacenRepuestos_PortClient() {
        }
        
        public AlmacenRepuestos_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenRepuestos_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenRepuestos_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenRepuestos_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.RegistrarEntrega(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request) {
            return base.Channel.RegistrarEntrega(request);
        }
        
        public void RegistrarEntrega(string codEmpleado) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega();
            inValue.codEmpleado = codEmpleado;
            RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result retVal = ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).RegistrarEntrega(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result> RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.RegistrarEntregaAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request) {
            return base.Channel.RegistrarEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result> RegistrarEntregaAsync(string codEmpleado) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega();
            inValue.codEmpleado = codEmpleado;
            return ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).RegistrarEntregaAsync(inValue);
        }
    }
}
